corePath <- '~/WebHub/images/'

dashboards <- c('Dashboard_InstrumentQC','Dashboard_InstrumentRMA','Dashboard_InstrumentNCR','Dashboard_BioReagentNCR',
                'Dashboard_ComplaintInvestigation','Dashboard_CustomerComplaints','Dashboard_InternalReliability',
                'Dashboard_InstrumentVOE','Dashboard_PouchManufacturingQuality','Dashboard_PouchQC','Dashboard_InstrumentManufacturing',
                'Dashboard_InstrumentServicing','Dashboard_InstrumentCalibration','Dashboard_SupplierReliability','Dashboard_ProgramManagement',
                'Dashboard_Contamination', 'Dashboard_PRE', 'Dashboard_Trends', 'Dashboard_GoLiveToThrive', 'Dashboard_PouchSPC', 'Dashboard_CustomerSupport')

copyPath.gd <- '\\\\Filer01/Data/Departments/PostMarket/~Dashboards/WebHub/images/'
copyPath.it <- '\\\\biofirestation/WebHub/WebHub/images/' 

# copy all the images that are generated on the PROD server
for (i in 1:length(dashboards)) {
  
  localPath <- paste(corePath,dashboards[i],sep='')
  files <- list.files(path=localPath)
  gdPath <- paste(copyPath.gd,dashboards[i],sep='')
  itPath <- paste(copyPath.it,dashboards[i],sep='')  
  
  for (j in 1:length(files)) {
    
    fileName <- paste(localPath,'/',files[j],sep='')
    file.copy(fileName, gdPath, overwrite=TRUE)
    file.copy(fileName, itPath, overwrite=TRUE)
  }
}

# copy over the images generated by the Pouch Final QC tool built by BioMath and add them to the same directory where the PostMarket
# Pouch Final QC images are stored
files <- list.files(paste(copyPath.gd,'Dashboard_PouchQC',sep=''))
for(k in 1:length(files)) {
  
  fileName <- paste(copyPath.gd,'Dashboard_PouchQC','/',files[k],sep='')
  file.copy(fileName, paste(copyPath.it,'Dashboard_PouchQC',sep=''),overwrite = TRUE)
}

rm(list=ls())