# THIS IS THE FILE USED TO PULL ALL DATA NEEDED FOR THE RMA DASHBOARD FROM SQL
#*note: to set DB paths go to Control Panel/Systems & Security/Administrative Tools/Data Sources (ODBC)
source('Rfunctions/loadSQL.R')

PMScxn = odbcConnect("PMS_PROD")
loadSQL(PMScxn, "SQL/R_IVOE_PlungerGasketCreepByPart.sql", "gasketCreep.df")
loadSQL(PMScxn, "SQL/R_IVOE_WindowBladderFailureByLot.sql", "bladderLots.df")
loadSQL(PMScxn, "SQL/R_IVOE_LidFailuresByPart.sql", "lids.df")
loadSQL(PMScxn, "SQL/R_IRMA_RMAsShippedByInstrumentVersion.sql", "rmaShipped.df")
loadSQL(PMScxn, "SQL/R_CC_CustPouchesShippedDetailed.sql", "pouches.df")
loadSQL(PMScxn, "SQL/R_IVOE_Board.sql", c("boardsInField.df", "boardFailureRMA.df", "boardNCR.df"))
loadSQL(PMScxn, "SQL/R_IVOE_Thermoboard.sql", "board.thermo.df")
loadSQL(PMScxn, "SQL/R_IVOE_ValveBoard.sql", "board.valve.df")
loadSQL(PMScxn, "SQL/R_IVOE_ImageMasterBoard.sql", "board.image.df")
loadSQL(PMScxn, "SQL/R_IVOE_CameraBoard.sql", "board.camera.df")
loadSQL(PMScxn, "SQL/R_IVOE_LEDExcitationError.sql", "excitation.df")
loadSQL(PMScxn, "SQL/R_IVOE_SealBarAlignmentNCR.sql", "sealBarNCR.df")
loadSQL(PMScxn, "SQL/R_IVOE_SealBarAlignmentRMA.sql", "sealBarRMA.df")
loadSQL(PMScxn, "SQL/R_IVOE_WireHarnessNCR.sql", "wireharnessNCR.df")
loadSQL(PMScxn, "SQL/R_IVOE_WireHarnessRMA.sql", "wireharnessRMA.df")
loadSQL(PMScxn, "SQL/R_IRMA_NewCompShip.sql", "compShip.df")
loadSQL(PMScxn, "SQL/R_IRMA_ComputerEarlyFailure.sql", "computerEF.df")
loadSQL(PMScxn, "SQL/R_INCR_InstrumentsProduced_denom.sql", "newInst.df")
loadSQL(PMScxn, "SQL/R_IVOE_LooseScrewRMA.sql", "looseScrew.df")
loadSQL(PMScxn, "SQL/R_IVOE_EdgeLoadComplaints.sql", "edgeLoad.df")
close(PMScxn)
