getCodeFromDescrip <- function(codeDescrip) {
  
  codeAsInt <- switch(codeDescrip,
                      '100 - Hard Seal Gasket Leak' = 100,
                      '103 - Molded Bladder Leak' = 103,
                      '109 - Dirty/Damaged Component Affecting Optics' = 109,
                      '110 - Valve Faulty' = 110,
                      '115 - General Manifold Failure' = 115,
                      '503 - PCR1 Calibration' = 503,
                      '504 - PCR2 Calibration' = 504,
                      '507 - Peltier Delamination' = 507,
                      '509 - General Peltier Failure' = 509,
                      '110 - Faulty Valve' = 110,
                      '203 - Plunger Block Leak (non-valve)' = 203,
                      '204 - Gasket Creep Affecting Plunge' = 204,
                      '205 - Plunger Corrosion Affecting Plunge' = 205,
                      '209 - Excess Grease Affecting Plunge' = 209,
                      '207 - General Plunger Block Failure' = 207,
                      '600 - LED Failure' = 600,
                      '601 - Photodiode Board Failure' = 601,
                      '602 - Alignment Needed' = 602,
                      '604 - Calibration Needed' = 604,
                      '605 - Defective 1.5 Camera' = 605,
                      '607 - Defective 2.0 Camera' = 607,
                      '52 - Window Bladder Affecting Optics' = 52,
                      '109 - Dity/Damaged Component Affecting Optics' = 109,
                      '51 - Delamination (no leak)' = 51,
                      '52 - Affecting Optics' = 52,
                      '53 - Leak' = 53,
                      '0 - Unable to Reproduce' = 0,
                      '2 - Customer Abuse/Tampering' = 2,
                      '3 - Loaner Return' = 3,
                      '4 - Loose Screw' = 4,
                      '5 - Communication Error (unable to reproduce)' = 5,
                      '9 - Pinched/Kinked Hose' = 9,
                      '10 - Damaged During Shipping' = 10,
                      '11 - Wire Hareness Disconnected' = 11,
                      '12 - Fan Inoperable' = 12,
                      '13 - PM Performed' = 13,
                      '14 - Defective Wire Harness' = 14,
                      '17 - Noisy Fan Operation' = 17,
                      '18 - Wire Harness in Wrong Location' = 18
  )
  
  return(codeAsInt)
}
