library(RODBC)

#---- Query list of active properties and object properties used by Trackers
PMScxn = odbcConnect("PMS_PROD")

query = readLines("TrackerProperties.sql")
query = paste(query,collapse="\n")
properties.df = sqlQuery(PMScxn,query)

query = readLines("TrackerObjectProperties.sql")
query = paste(query,collapse="\n")
objectProperties.df = sqlQuery(PMScxn,query)

# query = readLines("TrackerStages.sql")
# query = paste(query,collapse="\n")
# stages.df = sqlQuery(PMScxn,query)

close(PMScxn)
#----------------------------------------------------------

processTrackerName = function(trackerName){
  if(trackerName=='COMPLAINT'){
    trackerName='Complaint';
  }
  trackerName;
}

processObjectName = function(trackerName, objectName){
  objectName = gsub("[^a-zA-Z]","", objectName);
  if(startsWith(objectName,trackerName)){
    objectName = substr(objectName, nchar(trackerName)+1, nchar(objectName));
  }
  paste(trackerName,objectName,sep="");
}

processPropertyName = function(propertyName){
  gsub("[^a-zA-Z]","", propertyName)
}

sink("CreateProc.sql")

cat("-- This file was auto-generated by createProc.R and should not be modified.
USE PMS1
GO

IF OBJECT_ID('[dbo].[bUpdateTrackerTables]') IS NOT NULL
DROP PROCEDURE [dbo].[bUpdateTrackerTables]
GO

CREATE PROCEDURE [dbo].[bUpdateTrackerTables]
AS
");

for(t in unique(properties.df$Tracker)){
  trackerName = processTrackerName(t);
  df = properties.df[properties.df$Tracker == t,];
  tables = unique(as.character(df$Table));
  
  #------- Create tracker view ------
  cat("BEGIN TRAN;\n");
  cat("WITH [Props] ([TicketId], [PropertyId], [TrackablePropertyId]) AS (
SELECT 
  BT.[TicketId],
  P.[PropertyId], 
  P.[TrackablePropertyId]
FROM [RO_TRACKERS].[Trackers].[dbo].[BaseTicket] BT WITH(NOLOCK)
LEFT JOIN [RO_TRACKERS].[Trackers].[dbo].[TicketStages] TS WITH(NOLOCK) ON BT.[TicketId] = TS.[TicketId]
LEFT JOIN 	(
  SELECT 
    GTH.[TicketStageId],
    MAX(GTH.[GeneralTicketHistoryId]) AS [GeneralTicketHistoryId]
  FROM [RO_TRACKERS].[Trackers].[dbo].[GeneralTicketHistories] GTH WITH(NOLOCK)
  GROUP BY GTH.[TicketStageId]
) GTH ON GTH.[TicketStageId] = TS.[TicketStageId]
LEFT JOIN [RO_TRACKERS].[Trackers].[dbo].[TicketProperties] TP WITH(NOLOCK) ON TP.[GeneralTicketHistoryId] = GTH.[GeneralTicketHistoryId]
LEFT JOIN [RO_TRACKERS].[Trackers].[dbo].[Properties] P WITH(NOLOCK) ON P.[PropertyId] = TP.[PropertyId]
),
");
  cat(paste(sapply(1:length(tables),function(i){
    if(tables[i]=="CheckboxProperties"){
      paste("[",tables[i],"] ([TicketId], [PropertyId], [TrackablePropertyId], [RecordedValue]) AS (
SELECT P.[TicketId], P.[PropertyId], P.[TrackablePropertyId], CAST(T.[RecordedValue] AS SMALLINT)
FROM [Props] P LEFT JOIN [RO_TRACKERS].[Trackers].[dbo].[",tables[i],"] T WITH(NOLOCK) ON P.[PropertyId] = T.[PropertyId]
      )",sep="")
  }else{
    paste("[",tables[i],"] ([TicketId], [PropertyId], [TrackablePropertyId], [RecordedValue]) AS (
SELECT P.[TicketId], P.[PropertyId], P.[TrackablePropertyId], T.[RecordedValue]
FROM [Props] P LEFT JOIN [RO_TRACKERS].[Trackers].[dbo].[",tables[i],"] T WITH(NOLOCK) ON P.[PropertyId] = T.[PropertyId]
    )",sep="")
  }
    }),collapse=",\n"));
  cat("
SELECT
BT.[TicketId],
BT.[CreatedDate],
BT.[Status],
BT.[CreatedBy],
BT.[TicketString],
BT.[LastModified],
BT.[InitialCloseDate],");
  cat(paste(sapply(1:nrow(df),function(i){
    paste("
(SELECT MAX([RecordedValue]) FROM [",
          df$Table[i],
          "] T WHERE T.[TicketId] = BT.[TicketId] AND T.[TrackablePropertyId]=",
          df$TrackablePropertyId[i],
          ") AS [",
          processPropertyName(df$Name[i]),
          "]",
          sep=""
          ) }
    ),
    collapse=","));
cat("\nINTO [dbo].[");
cat(trackerName);
cat("_TEMP]");
cat("\nFROM [RO_TRACKERS].[Trackers].[dbo].[BaseTicket] BT WITH(NOLOCK)
WHERE BT.[Tracker] = '");
    cat(trackerName);
    cat("' AND BT.[Status] NOT IN ('ClosedVoided','ClosedDuplicate')\n");
cat("ALTER TABLE [dbo].[");
cat(trackerName);
cat("_TEMP] ADD PRIMARY KEY (TicketId);\n");

cat("CREATE INDEX IDX_TicketId ON [dbo].[");
cat(trackerName);
cat("_TEMP]([TicketId])\n");

cat("CREATE INDEX IDX_TicketString ON [dbo].[");
cat(trackerName);
cat("_TEMP]([TicketString])\n");

cat("CREATE INDEX IDX_CreatedDate ON [dbo].[");
cat(trackerName);
cat("_TEMP]([CreatedDate])\n");

cat("CREATE INDEX IDX_Status ON [dbo].[");
cat(trackerName);
cat("_TEMP]([Status])\n");
  
cat("IF OBJECT_ID('[dbo].[");
cat(trackerName);
cat("]') IS NOT NULL
DROP TABLE [dbo].[")
cat(trackerName);
cat("];\n");
cat(paste0("EXEC sp_rename 'dbo.", trackerName, "_TEMP', '", trackerName, "'\n"));

cat("COMMIT
");
}
for(t in unique(properties.df$Tracker)){
  trackerName = processTrackerName(t);
  df = properties.df[properties.df$Tracker == t,];
  tables = unique(as.character(df$Table));
  
  #-------- Create object tables ---------
  for(objectName in unique(subset(objectProperties.df,objectProperties.df$Tracker==t)$ObjectName)){
      tableName = processObjectName(trackerName,objectName);
      df = objectProperties.df[objectProperties.df$Tracker == t & objectProperties.df$ObjectName==objectName,];
      tables = unique(as.character(df$Table));
      cat("BEGIN TRAN;\n");
      cat("WITH
[Objects] ([TicketId], [ObjectId], [TrackableObjectId]) AS (
SELECT
  BT.[TicketId],
  TKO.[ObjectId],
  OB.[TrackableObjectId]
FROM [RO_TRACKERS].[Trackers].[dbo].[BaseTicket] BT WITH(NOLOCK)
LEFT JOIN [RO_TRACKERS].[Trackers].[dbo].[TicketStages] TS WITH(NOLOCK) ON BT.[TicketId] = TS.[TicketId]
LEFT JOIN 	(
  SELECT
    GTH.[TicketStageId],
    MAX(GTH.[GeneralTicketHistoryId]) AS [GeneralTicketHistoryId]
  FROM [RO_TRACKERS].[Trackers].[dbo].[GeneralTicketHistories] GTH WITH(NOLOCK)
  GROUP BY GTH.[TicketStageId]
) GTH ON GTH.[TicketStageId] = TS.[TicketStageId]
LEFT JOIN [RO_TRACKERS].[Trackers].[dbo].[TicketObjects] TKO WITH (NOLOCK) ON GTH.[GeneralTicketHistoryId] = TKO.[GeneralTicketHistoryId]
LEFT JOIN [RO_TRACKERS].[Trackers].[dbo].[Objects] OB WITH (NOLOCK) ON OB.[ObjectId] = TKO.[ObjectId]
),
[Props] ([ObjectId], [PropertyId], [TrackablePropertyId]) AS (
SELECT
  OP.[ObjectId],
  P.[PropertyId],
  P.[TrackablePropertyId]
FROM [RO_TRACKERS].[Trackers].[dbo].[ObjectProperties] OP WITH (NOLOCK)
LEFT JOIN [RO_TRACKERS].[Trackers].[dbo].[Properties] P WITH (NOLOCK) ON OP.[PropertyId] = P.[PropertyId]
),
");
      cat(paste(sapply(1:length(tables),function(i){
        if(tables[i]=="CheckboxProperties"){
          paste("[",tables[i],"] ([ObjectId], [PropertyId], [TrackablePropertyId], [RecordedValue]) AS (
SELECT P.[ObjectId], P.[PropertyId], P.[TrackablePropertyId], CAST(T.[RecordedValue] AS SMALLINT)
FROM [Props] P LEFT JOIN [RO_TRACKERS].[Trackers].[dbo].[",
        tables[i],
        "] T WITH(NOLOCK) ON P.[PropertyId] = T.[PropertyId]
)",sep="")
        }else{
          paste("[",tables[i],"] ([ObjectId], [PropertyId], [TrackablePropertyId], [RecordedValue]) AS (
SELECT P.[ObjectId], P.[PropertyId], P.[TrackablePropertyId], T.[RecordedValue]
FROM [Props] P LEFT JOIN [RO_TRACKERS].[Trackers].[dbo].[",
                tables[i],
                "] T WITH(NOLOCK) ON P.[PropertyId] = T.[PropertyId]
)",sep="")
        }
  }),collapse=",\n"));
      cat("
SELECT
BT.[TicketId],
BT.[CreatedDate],
BT.[Status],
BT.[CreatedBy],
BT.[TicketString],
BT.[LastModified],
BT.[InitialCloseDate],
O.[ObjectId],");
      cat(paste(sapply(1:nrow(df),function(i){
        paste("
(SELECT MAX([RecordedValue]) FROM [",
              df$Table[i],
              "] T WHERE T.[ObjectId] = O.[ObjectId] AND T.[TrackablePropertyId]=",
              df$TrackablePropertyId[i],
              ") AS [",
              processPropertyName(df$PropertyName[i]),
              "]",
              sep=""
              ) }
        ),
        collapse=","));
      cat("\nINTO [dbo].[");
      cat(tableName);
      cat("_TEMP]");
      cat("
FROM [RO_TRACKERS].[Trackers].[dbo].[BaseTicket] BT WITH(NOLOCK)
INNER JOIN [Objects] O ON BT.[TicketId] = O.[TicketId]
WHERE BT.[Tracker] = '");
      cat(t);
      cat("' AND O.[TrackableObjectId]=");
      cat(df$TrackableObjectId[1]);
      cat(" AND BT.[Status] NOT IN ('ClosedVoided','ClosedDuplicate')\n");

      cat("CREATE INDEX IDX_TicketId ON [dbo].[");
      cat(tableName);
      cat("_TEMP]([TicketId])\n");
      
      cat("CREATE INDEX IDX_TicketString ON [dbo].[");
      cat(tableName);
      cat("_TEMP]([TicketString])\n");
      
      cat("CREATE INDEX IDX_CreatedDate ON [dbo].[");
      cat(tableName);
      cat("_TEMP]([CreatedDate])\n");
      
      cat("CREATE INDEX IDX_Status ON [dbo].[");
      cat(tableName);
      cat("_TEMP]([Status])\n");
      
      cat("IF OBJECT_ID('[dbo].[");
      cat(tableName);
      cat("]') IS NOT NULL
          DROP TABLE [dbo].[")
      cat(tableName);
      cat("];\n");
      cat(paste0("EXEC sp_rename 'dbo.", tableName, "_TEMP', '", tableName, "'\n"));
      cat("COMMIT\n\n");
  }
}

cat("GO
")  

sink();